### ISSUE TITLE
Suggestions to reduce the redundancy of the set functions

### ISSUE THREAD

**Issue by dallenroberts** [vando026/ahri#2]
Just went through the set functions again. I think it would be a lot simpler just with setArgs() and setData() (and the helper functions like getBirthDate). If setData can really work on any of the datasets, I don’t see why there is any need for setHIV or setEpisodes. And if setArgs can also subset by age and sex, I’m not sure why you need setAge. Maybe I’m missing the use case for the other functions, but in my opinion it’s more confusing to have overlapping functions with similar names. Last, I would make the defaults for these functions to include all years and all ages (not just 15-54, but all ages). It’s a bit deceptive to run something like setArgs(Age = c(15,25)) and also drop years < 2004 and > 2018. Plus, if people are using these functions on other datasets, like when 2019 data gets released, then it’s not intuitive to only keep 2005-2018 data. You’re going to have to keep updating the function defaults with every data release unless you change the defaults to just include everything unless otherwise specified

**Comment by vando026** [comment]
Hi, these are great questions. 

setHIV and setEpisodes are most certainly needed and useful. In the ahri code base, these
two functions are called frequently. setHIV for example is just a shorthand for  

```r
Args = setArgs()
hiv = getHIV()
hdat = setData(hiv, Args)
```
You are welcome to use this pattern for your needs, but if you find yourself repeating
this pattern you should use setHIV (and by extension setEpisodes). In addition, setHIV
makes it quicker and easier to do things like:

```r
getAgeYear(dat=setHIV(Args))
```
Stand alone functions such as setAge allow for existing code/functions to be reused for specific needs. (The function setHIV is a good example of this). setAge will do the job only for setting age, setData will do the job for setting year and age and sex, etc. I would not say that this is code redundancy.  Here, smaller functions are being used to compose larger functions: setData for example, calls setAge, and setHIV calls setData.  These function names are documented with most having examples, and there are wiki help files, with a bit of effort, the user should not be too confused.

Regarding the defaults: they are not perfect but they are sensible. HIV test years are
only considered valid from 2004. Currently, I have 2005 as the lower limit for Years in setArgs.
I am happy to update the upper year limit to the latest year (this only needs to be
done once a year). The age defaults are based on the HIV testing ages. 

setArgs was designed to enable the user to create and reuse various parameter settings. 

For the HIV dataset you could do something more specific like

```r
hiv_args = setArgs(Age=list(Mal=c(15, 54), Fem=c(15, 49)))
setHIV(hiv_args)
```
And for the Episodes something different by selecting all ages:

```r
epi_args = setArgs(Age=list(All=c(0, 100)))
setEpisodes(epi_args)
```

Using setArgs is a conscious step. The trade-off for the convenience of setArgs and
other set functions is that the user must make an effort to consciously set the
appropriate paramaters or acknowledge the default ones. Here, the user is warned of doing
Args = setArgs() without first examining what the default parameters are. I have now added
this warning to the ahri help files.

**Comment by vando026** [comment]
Hi Allen, I am thinking to revisit the issue of the default paramters for setArgs. In some preliminary tests, the code does not break if you do something like setArgs(Years=c(1998, 2025)), which includes all relevant years, and similarly for Age > 0. 

I will have to do a series of tests just to make sure that setting out of bound values (ie 2025) doesnt lead to code breakage.  So the default values may become more inclusive over time (rather than being based on HIV analyses) as I do the checks.

**Comment by vando026** [comment]
Version 0.9.0 now includes new default paramater settings for the Age and Year arguments. So setArgs will include all years and all ages between 0 and 100 years as the default. I added some additional tests, but will keep an eye on any potential breakages to code.
